# Generated by Django 5.2 on 2025-04-08 16:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_room_room_members_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=users.models.generate_room_id, editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
